### ISSUE TITLE
[SNCU] 1058 Support ticket changes

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/SNCU#15]
Add the new locations highlighted in yellow color

https://avni.freshdesk.com/a/tickets/1058

**Comment by nupoorkhandelwal** [comment]
Failed to parse multipart servlet request; nested exception is java.io.IOException: The temporary upload location [/tmp/tomcat.7537077700625527723.8021/work/Tomcat/localhost/ROOT] is not valid


Upload on Production is not working. Getting above error.

**Comment by garimadosar5** [comment]
QA Notres-  
- Umran Village is twice in the system.

![Screen Shot 2021-01-27 at 1.53.52 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/aa3a2476-2abc-4594-be9c-cdb584390c63)

**Comment by nupoorkhandelwal** [comment]
Fixed
