### ISSUE TITLE
[SNCU] Support ticket #1132

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/SNCU#17]
https://avni.freshdesk.com/a/tickets/1132

Add one more column in each of the following reports to show total count of individuals whose status is not available /No visit data.

- [x] Child_growth_monitoring

- [x] Child_growth_monitoring_7_month_to_5_year

- [x] Growth_Monitoring_nutritional_status

**Comment by garimadosar5** [comment]
QA Notes - 
- report - https://reporting-jasper.avniproject.org/jasperserver/flow.html?_flowId=viewReportFlow&_flowId=viewReportFlow&ParentFolderUri=%2FSNCU%2FReports%2FAggregates&reportUnit=%2FSNCU%2FReports%2FAggregates%2FChild_growth_monitoring_7_month_to_5_year_&standAlone=true

showing like this.
![Screen Shot 2021-02-25 at 12.40.59 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/819fa9fc-5d2a-4238-8091-e3e3b08257e5)
