### ISSUE TITLE
[SNCU] Offline indicators dashboard reports

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/SNCU#18]
https://docs.google.com/spreadsheets/d/1DJzjWi_Pde0pDQLdDNTzG3QkrJZ1MREs/edit#gid=1401064288

**Program -Child**

- [x] At birth Low Birth weight Children

- [x] Children with Congenital Anomaly

- [x] At the age of 7 months SAM Children

- [x] Total SAM Children ( 6 to 5 years Age) 

- [x] Total MAM Children ( 6 to 5 years Age) 

- [x] Current sick Children 

- [x] At 13 months children Complete Immunization status

- [x]  List of died children

- [x] List of permanent migrated children

**Comment by garimadosar5** [comment]
QA Notes - 
- Low birth weight children report is not taking children with 2 kg of weight. Case "child a", this child has birth weight 2 Kg. **Fixed**
