### ISSUE TITLE
[SNCU][Support] Vaccination list is not showing for few children.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/SNCU#20]
https://avni.freshdesk.com/a/tickets/1231

For few children, page is showing as blank black screen. Name are mentioned in the sheet.
![1620732730922.JPEG](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/399a4ece-af71-4c53-b3c5-51897eea95e3)

**Comment by nupoorkhandelwal** [comment]
Most of the children have proper vaccination schedules as per their age. Seems to be a sync issue.

 Have replied on the ticket accordingly.
