### ISSUE TITLE
[SNCU New Reports] Registration Form Based Reports

### ISSUE THREAD

**Issue by arjunk** [avniproject/SNCU#25]
https://docs.google.com/spreadsheets/d/1K5421m3LjHgrhFgpLr_3v-QZrS9I0MT5/edit#gid=730045627

**Comment by garimadosar5** [comment]
**QA Notes -** 
- In this report, the page is too big. That is not causing any issue here on web but if I try and download and print as pdf, it prints very small font numbers and there is a big part s the page that is blank.
- Mother's education is non mandatory question so add one more row "data not captured".

**Fixed**
