### ISSUE TITLE
[SNCU New Reports] SNCU Form Report

### ISSUE THREAD

**Issue by arjunk** [avniproject/SNCU#26]

**Comment by garimadosar5** [comment]
QA Notes - 
- table breaking.
![Screen Shot 2021-11-11 at 1.43.19 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/1e4c04fb-0150-458d-bb45-0c6a46e4f15a)
- Please add "data not collected" in the reports where questions are non mandatory or skipped. (and please name it as data not available or data not collected. do not name it as NONE.)
- What is about exit cases? How to distinguish exited cases in the report?
- Filter - ![Screen Shot 2021-11-11 at 2.18.29 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/f4b558ab-1c0c-459b-adab-11e4ec5a26e2)
- Is there a need to put decimal in both the age columns?
- Line list column "Weight at the time of" is incomplete.

**Comment by garimadosar5** [comment]
QA Notes - 2

https://images.zenhubusercontent.com/298572986/dc64bd8d-26f2-4752-8c37-6ba116bb9400/error.mov
- Point 1 is not done. Is it not required? **There is no non-mandatory indicator in this report.

Fixed the scroll issue.**

**Comment by garimadosar5** [comment]
**QA Notes - 3**
- Child's First visit	
- Congenital Anomaly	
These two numbers are not equal to total enrolments. you should add one more indicator "data not capture" or whatever is applicable.
Let me know if there is any question. **Added**
