### ISSUE TITLE
[SNCU New Reports] Cohort wise children report

### ISSUE THREAD

**Issue by arjunk** [avniproject/SNCU#27]
https://docs.google.com/spreadsheets/d/1K5421m3LjHgrhFgpLr_3v-QZrS9I0MT5/edit#gid=730045627

Filter same as old report

**Comment by garimadosar5** [comment]
QA Notes - 
- Nutrational status filter is giving this error. **Fixed**
![Screen Shot 2021-11-19 at 5.24.58 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/882dc2ad-4c06-4338-b032-efb7d0281b5b)

- On filter - "Exited = YES", not showing right data. Only Not applicable columns are showing data. **The data in report starts from 6th-7th month interval. And all the program encounters of the exited cases have been completed on the same day of enrolment. So they wont get considered.**
- There are 0 exit cases showing in the report. but there are 500+ exit cases in this program.- **From where did u get this count? There are only 117 exit cases.**
- All the children after April 21 cohort, showing in not applicable column. only 5 children are there in April 21 to sep 21 cohort in 0-6 months of age. **0-6 months column doesn't show children of 0-6 months age. Instead it holds count of children who have 6-7months difference between 'Child Followup' and enrolment.**

**Comment by nupoorkhandelwal** [comment]
These three children dont have "Date of discharge from SNCU" in their enrolment, so they are getting missed in the cohort--
Vishal sunita gulab	Vasava
Shivam manisha jayendra	Vasava
Shareyansh  Shardaben Jaysing Govindbhai	Vasava

**Comment by garimadosar5** [comment]
**QA Notes -** 
- Cohort should show in a sequence. 
- Sum of subcategory is not matching to Total enrolled.
for eg: cohort - Apr 20 to Sep 20 and Apr 21 to Sep 21
![Screen Shot 2021-11-29 at 9.28.43 AM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/d2a6c677-395c-4282-affe-88f1781d1959)
