### ISSUE TITLE
[SNCU New Reports] SNCU Milestone Report

### ISSUE THREAD

**Issue by arjunk** [avniproject/SNCU#28]
https://docs.google.com/spreadsheets/d/1K5421m3LjHgrhFgpLr_3v-QZrS9I0MT5/edit#gid=730045627&range=27:27

Filters same as older reports

**Comment by garimadosar5** [comment]
**QA Notes -** 
- In all the LL all the cases are showing. for eg: If we click on children who completed milestone 13 number, it will show the list of all the children.
- apply date filter and then click on LL, gives server error.
![Screen Shot 2021-11-29 at 5.37.35 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/7ab1e6e3-719d-483e-b9f1-7de7b0f201e4)
