### ISSUE TITLE
[SNCU] SNCU Registartion Form

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/SNCU#3]
https://docs.google.com/spreadsheets/d/1DJzjWi_Pde0pDQLdDNTzG3QkrJZ1MREs/edit#gid=178123144

**Comment by garimadosar5** [comment]
QA Notes- 
- I can fill the "number of family members" = 0 **Fixed**
- Subcaste is not given in the requirement sheet. **Updated**
- Decision maker in the family. We can remove "father-in-law" and "mother-in-law". **Updated**
- Question "Any congenital abnormality?" is not there. "Specially abled" is asked. and when YES is selected, question "please specify" does not appear. **Fixed**
