### ISSUE TITLE
[SNCU New Reports] Fully Vaccinated Children

### ISSUE THREAD

**Issue by arjunk** [avniproject/SNCU#30]
https://docs.google.com/spreadsheets/d/1K5421m3LjHgrhFgpLr_3v-QZrS9I0MT5/edit#gid=730045627

Filters same as older reports

**Comment by nupoorkhandelwal** [comment]
Moving this card on hold as currently unable to move the report to jasper server due to prod read db being slow/ not responding

**Comment by garimadosar5** [comment]
**QA Notes -** 
- Add total in the report.

**Comment by garimadosar5** [comment]
**QA Notes -** 
- Age and Age in months, remove decimal.
- Show vaccines in a sorting manner when it was given age wise. right now it is random and it is difficult to find out what child has got what medicine. **How can we show vaccines age wise? Currently i have updated it to show according to completiotn date wise.**

**Comment by garimadosar5** [comment]
QA Notes - 
- report giving this error.
![Screen Shot 2021-11-29 at 4.09.32 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/beefa099-7568-4928-a8c1-e8bc967dd05a)
