### ISSUE TITLE
[SNCU] Removing permanently migrated and expired children from dashboard count.

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/SNCU#36]
Children who have permanently migrated or died are not required be counted for following cards in Dashboard as these children are either out of program area or have died.

Permanently migrated or Child Death is recorded in reason of a cancelled visit or when a child is exited from program. Exited children are already excluded from the count, need to exclude children who have been permanently migrated or died but user has forgotten to exit.

Cards (existing) where the change need to be done:

- [ ] Low birth weight 
- [ ] children with congenital anomaly
- [ ] Children at 7 months in SAM
- [ ] Total SAM Children
- [ ] Total MAM Children
- [ ] Currently sick children
- [ ] At 13 months children completely immunized

**Comment by nupoorkhandelwal** [comment]
Moving this card on hold as the process to fetch cancel form observations is not clear.

https://app.zenhub.com/workspaces/product-635b73bded85e50018871ae6/issues/avniproject/avni-server/488

**Comment by utkarshavni** [comment]
Closing this since there was no platform issue and the children have been exited through script.
