### ISSUE TITLE
[SNCU] Visit scheduling change on cancelling a Child follow-up

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/SNCU#38]
**Use case scenario:**
There are cases where a follow-up visit of child is cancelled due to Absence of child, Absence of field worker or Hospitalization. In this situation, when the next program visit is scheduled after a period couple of months or longer, there is no interaction with beneficiary in between. 

**Goal**
 The cancelled visit should be rescheduled after two weeks - when the reason for cancellation are:
1.  Out of village
2.  Field worker on leave
3.  Hospitalization
4. Other

The cancelled visit should not be rescheduled when the reason for cancellation are:
1.  Child death
2. Permanent migration

**The logic will only apply to Follow-up visits and not PNC visits.**

**Reference sheet**
https://docs.google.com/spreadsheets/d/1nasW7-8Rpg2puQJYSV7Nrr4OHMOpXLMN/edit#gid=2046022318
The green cells for "On Cancel" visit column has changes mentioned.

**Test scenarios:**
Check the reference sheet given above and test one or two cases from each category of child.

**Comment by AchalaBelokar** [comment]
- [ ] If am cancel the visit current date it is showing after 2 weeks date

**Comment by AchalaBelokar** [comment]
1st visit is schedule 8 dec 2022 after that I change the date 25 dec and then I cancel the visit then this visit is scheduled on 22 dec . can you check this

**Comment by Gojo-Taqi** [comment]
No code changes were done

**Comment by utkarshavni** [comment]
@Gojo-Taqi As Achala has explained, schedule the next visit after cancellation based on the date given in cancellation (not based on the date it was earlier scheduled).

Also, make sure that when the follow-up gets scheduled after 14 days of cancellation and when that follow-up is completed, it schedules the next follow-up based on Child's age of that day and Nutritional status (Normal/SAM/MAM) - attaching sheet here for reference.

https://docs.google.com/spreadsheets/d/1nasW7-8Rpg2puQJYSV7Nrr4OHMOpXLMN/edit#gid=2046022318
