### ISSUE TITLE
[SNCU] Program exit for permanently migrated and expired Children.

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/SNCU#39]
Ticket reference:
https://avni.freshdesk.com/a/tickets/2213

At times, users forget to perform Program Exit visit for a child who has permanently migrated or died. This results in wrong data reporting.

While cancelling a visit for a child, reason for Permanent migration or Child death is provided. 

Exit from backend all the children enrolled in the program who have permanently migrated or Died.

**Comment by nupoorkhandelwal** [comment]
https://github.com/avniproject/SNCU/blob/master/data%20migrations/FD2213%20Adding%20program%20exit%20for%20permantly%20migrated%20and%20death%20cases

@sachsk  please review these scripts.

**Comment by nupoorkhandelwal** [comment]
On UAT -
Permanent migrated -
Amarnath Kant
baby usha lalsing vasava

Child death -
Child 2 Surname
Baby Suman
