### ISSUE TITLE
[SNCU] SNCU Enrolment form

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/SNCU#4]
https://docs.google.com/spreadsheets/d/1DJzjWi_Pde0pDQLdDNTzG3QkrJZ1MREs/edit#gid=843094229

Form and visit scheduling on enrolment.

**Comment by garimadosar5** [comment]
QA Notes - 
- Question - "Diagnosis at the time of discharge?" this should be multi-select. **Done**

@garimadosar5  Please test visit scheduling on enrolment, as part of this card.
