### ISSUE TITLE
[SNCU] First PNC visit date change

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/SNCU#40]
Org: SNCU
Program: SNCU

When a Newborn child's birth weight is normal or less than 2 - First PNC is scheduled after 5 days from Discharge date of the child.

This has to change - First PNC is required to be recorded on the same day as that of enrollment. Rest of the PNC and follow-up will remain as it is.

Changes made in requirement sheet here in column B6 and B7 (only for the first point).
https://docs.google.com/spreadsheets/d/1nasW7-8Rpg2puQJYSV7Nrr4OHMOpXLMN/edit#gid=2046022318

**Comment by Gojo-Taqi** [comment]
Added the logic according to the card, took me 5 minutes to complete the card
