### ISSUE TITLE
[SNCU Support] Visit scheduling change for New born low birth weight

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/SNCU#41]
**Use case:**
For New born child who are low birth weight - the second visit right now happens on 14th day after the date of Discharge.  Since the enrollment can happen late, in that case the second visit might schedule on back date if the enrollment has happened couple of weeks after that.

**Goal:**
The second visit getting scheduled after first PNC to be scheduled on 14 days after the first PNC visit.

**Reference requirement sheet:**
https://docs.google.com/spreadsheets/d/1nasW7-8Rpg2puQJYSV7Nrr4OHMOpXLMN/edit#gid=2046022318
Cell reference: B7

**Test scenario:**
Apart from the use case mentioned above also check:
If first PNC is getting cancelled, then the second visit should be getting scheduled after 14 days after the scheduled date of the first PNC.

**Comment by sachsk** [comment]
earlier if child weight in the follow-up form is less than 3 then the 2nd visit was scheduling on the date of discharge + 14 days. but if child gets enroll after a month then that visit will get scheduled in past.
so to overcome this issue now we have scheduled the visit on the followup earliest date + 14 days.

**Comment by AchalaBelokar** [comment]
why it is showing child PNC 2 after doing 3 child PNC and after 12 jan it is scheduling the same date 12th jan Pls refer raja babu
 ![Screenshot 2022-12-15 at 10.28.57 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/a6214c73-b4f9-4377-9039-35069500e918)
