### ISSUE TITLE
[SNCU] Duplicate visit scheduled due to edit of enrollment

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/SNCU#45]
Steps to reproduce:
1. Register an individual in SNCU. 
2. Enroll in child program. First follow-up "Child follow-up" form is scheduled.
3. Complete the "Child follow-up". "Child follow-up 1" is scheduled based on the logic.
4. Now edit the enrollment and Save. It schedules the first follow-up again (which is already scheduled based on second step.) and "Child follow-up 1" is removed from planned visits.
5.  Now, Edit the "Child follow-up" from completed visits and it schedules "Child follow-up 1" that was removed.

Expected outcome:
When enrollment is edited, it should not schedule the next visit if it is already there in planned or completed visits. Edit scenarios are not handled right now.

**Comment by BEULAHEVANJALIN** [comment]
UAT bundle: [SNCU_UAT.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0lxQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d525953398483abf96188f548df1dcfbf646323d/SNCU_UAT.zip)

Prod bundle: [SNCU.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK01xQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6dc90f948ee1ee3107e17cd640e808e8c13fe361/SNCU.zip)

**Comment by Dinesh2019** [comment]
As per AC, the child follow-up is not scheduled to visit after editing the enrollment. But when we edit the follow-up visit it is rescheduled for the pervious visit.

Steps to reproduce;
1. Enroll in the child
2. Complete the follow-up visit 1 (eg: completed on the date 16/Oct/2023 and the next visit scheduled on 31/Oct/2023)
3. Edit the enroll excepted result in the child follow-up should not be scheduled again on 16/Oct/2023 Actual as excepted it is not scheduling
4. But when we complete the child follow-up 2 (eg: 31/Oct/2023 and the next visit scheduled on 15/Nov/2023)
5. If we edit the child followup -1 (eg: 16/0ct/2023 the scheduled visit is replaced by 31/Oct/2023) but excepted the latest visit should be scheduled without any update)

https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeG83QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8db222552d9b2fecdf9058d5034fe69cdf4691b5/Encounter%20edit%20scenario.mp4

**Comment by vedfordev** [comment]
@Dinesh2019  

Please check the bug card : https://github.com/avniproject/avni-models/issues/49

currently we can't handle edit encounter scenario. It is not raised by client.
