### ISSUE TITLE
[SNCU Support] Records to be voided 

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/SNCU#47]
Ticket reference:
https://avni.freshdesk.com/a/tickets/1747

UUIDs provided in attached document have to be voided along with enrollment and encounter details.
https://docs.google.com/spreadsheets/d/1lK9F7VpDWD1mjXBUGBJVmdKeh4PoBiOl/edit#gid=1880340386

**Comment by sachsk** [comment]
We have voided the individual and their enrolments and encounters.
