### ISSUE TITLE
[SNCU Support] Add a new column in an existing report

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/SNCU#50]
Linelist of Child growth monitoring - 7 months to 5 years

- [x] Add a new column Date (displaying the latest followup date) in the above report.
Support ticket - https://avni.freshdesk.com/a/tickets/2567

- [x] Remove column - Current nutritional status according to weight and age
https://avni.freshdesk.com/a/tickets/2563

**Add a new column Date displaying the _Followup date_ and _PNC Date_ wherever applicable in the following reports as well --**

- [x] Morbidity Status for Children Aged 0-59 Days
- [x] Child PNC Linelist
- [x] Growth Monitoring
- [x] Linelist for child growth monitoring
- [x] Linelist for KMC Care

**Comment by vedfordev** [comment]
@nupoorkhandelwal Completed "Linelist of Child growth monitoring - 7 months to 5 years" report.

**Comment by utkarshavni** [comment]
@vedfordev why is this card in Support? Is it done? what is pending?

**Comment by vedfordev** [comment]
@utkarshavni If you check support ticket they mentioned that do same thing with other relevant report but I don't know what are other relevant report

**Comment by arjunk** [comment]
@nupoorkhandelwal assigning this to you for analysis. can you identify the list of reports where we need to make this changes and then move this story in the ready lane?

**Comment by nupoorkhandelwal** [comment]
Estimates - 3hrs.
