### ISSUE TITLE
[SNCU Support] PNC visit getting scheduled twice

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/SNCU#51]
Support - https://avni.freshdesk.com/a/tickets/2534

- [ ] Try to reproduce the issue as mentioned and fix the logic on UAT first -

Example of a child:
Child name - Devyanshi Rupal Chirag Thakor Vasava 
UUID - 0ad72514-7d6c-449c-ad90-5ed2b9513aad

PNC scheduled of 7th April was scheduled twice - check completed visits screenshot in the ticket.
.

Unhandled Cases to handle - identified when fixing the ticket - not necessary for ticket fix but will be fixed as part of this card:
In contrast to the schedule mentioned here: https://docs.google.com/spreadsheets/d/1nasW7-8Rpg2puQJYSV7Nrr4OHMOpXLMN/edit#gid=2046022318 there are issues regarding the below in our current implementation:
- We are scheduling the 3rd visit after 50 days instead of 60 days
- If a normal visit, needs to be scheduled after low birth visit it should be after 28 days(instead of 28th day from first visit date) and overdue of normal visit should be 7 days gap.
- If a visit is done one day before due date, currently the same visit is scheduled again. Instead the next visit needs to be scheduled.
- If the date next visit is after 2 months, then it should not be a PNC visit instead a followup.
- If the followup data of PNC visit exceeds age of 2 months of the baby - then schedule followup visit instead of PNC.

Following cases tested in dummy catchment in UAT:
- N,N,N,F - uday sasha(individual firstname)
- N, L, L, N, F(can be normal or low birth) - normal low normal followup(individual firstname)

**Comment by AchalaBelokar** [comment]
- [ ] We are scheduling the 3rd visit after 50 days instead of 60 days
but it is sheduling after 57 days 
pls see the Individual  Yenu Yenu

**Comment by mahalakshme** [comment]
@AchalaBelokar we discussed this is not an issue right? can we move this to deploy ready?

**Comment by mahalakshme** [comment]
@AchalaBelokar the excel sheet was not updated with right values. have updated it now.
