### ISSUE TITLE
SAM and MAM Criteria Changes

### ISSUE THREAD

**Issue by arjunk** [avniproject/SNCU#54]
Source : https://avni.freshdesk.com/a/tickets/2867

After discussion with Dr. Dhiren below changes are finalised:

SAM and MAM criteria Changes:

- [x] 1. In growth Monitoring (Nutritional Status) line list, 1 extra column for Nutritional status based on weight for height will be added.

- [x] 2. for offline dashboard also Nutrition status should be according to weight for height from decision

- [x] 3. in Program summary also Nutrition status should be based on weight to height.

- [x] 4. Make change in rule for Nutritional Status on calculation of Nutritional Status of Child in Child Followup form, = 11.5 is now in MAM

- [x] 5. OEDEMA check to be removed from calculation.

- [x] 6. Cohort wise report should start showing nutrition status correctly for fresh data, old data correction is not required.

Below are Past discussion notes for reference:
Understand the scope of work from Vinay and provide estimates to get the budget approved
- Core issue was that we were looking at "Nutritional status" instead of "Nutritional Status based on Weight and Height"
- Changes to be done in app
1. In Growth Monitoring(nutritional status) Linelist, add 1 extra column - Nutritional status based on Weight for Height
2. Check the offline dashboard cards and consider only Nutritional status according to Weight for Height from the decision
3. Add  Nutritional status according to Weight for Height to the program summary as well
4. Make change in rule for Nutritional Status on calculation of Nutritional Status of Child in Child Followup form, = 11.5 is now in MAM
Muac < 11.5 is SAM (this is currently wrong)
MUAC >=11.5 and <= 12.5 is MAM
MUAC > 12.5 is Normal

Reports that consider the calculated Nutritional Status -
1.Child growth monitoring 7 month to 5 year
2.Cohort wise report
3.Growth Monitoring

- [x] We need to discuss with Dr.Dhiren if the reports needs to be updated or else its fine to just update the mentioned line list.

**Comment by nupoorkhandelwal** [comment]
Reports that consider the calculated Nutritional Status -

1.Child growth monitoring 7 month to 5 year
2.Cohort wise report
3.Growth Monitoring

**Comment by salilsamanvay** [comment]
OEDEMA check to be removed from calculation.

**Comment by sachsk** [comment]
Estimate : 4hr(beulah)

**Comment by BEULAHEVANJALIN** [comment]
---
- Children at 7 months in SAM (Includes non exited and non voided children) -> Uses "Nutritional status of child" observation.
-  Total SAM Children (non-exited and non-voided) -> Uses "Nutritional status of child" observation.
-  Total MAM Children (non-exited, non-voided and > 6 months) -> Uses "Nutritional status of child" observation.

##### Changed all the above cards to use "Current nutritional status according to weight and height".
---
##### Changed "Current nutritional status according to weight and age" to "Current nutritional status according to weight and height" in Child Enrolment Summary Rule
---
##### Changed the calculation for 'Nutritional Status of Child' in Child Followup form as follows:
- 'SAM':		muac <= 11.4
- 'MAM':		11.5 <= muac < 12.6
- 'Normal':	muac >= 12.6
---

**Comment by Dinesh2019** [comment]
Test Scenarios:
1. Create the individual with SAM nutrition and validate the count is added in this card Total SAM Children (non-exited and non-voided) 
2. Create the individual with MAM nutrition and validate the count is added to the card Total MAM Children (non-exited, non-voided, and > 6 months)
3. Create the individual with age 7 months and validate the count is added to the card Children at 7 months in SAM (Includes non - exited and non voided children
4. create the individual enrollment in the child and complete the first child follow-up from SAM and validate the count is added in the SAM dashboard after that complete the child - follow-up from SAM to MAM and validate the count is removed from SAM and add in the MAM 
5. create the individual enrollment in the child and complete the first child follow-up from MAM and validate the count is added in the MAM dashboard after that complete the child - follow-up from MAM to SAM and validate the count is removed from MAM and added in the SAM.
6. create the individual enrollment in the child and complete the first child follow-up from SAM and validate the count is added in the SAM dashboard after that complete the child - follow-up from SAM to MAM and validate the count is removed from MAM and add in the SAM, Complete the child follow - up MAM to Normal and validate the count is removed from MAM
7. Register the individual, enroll in the child program complete the child follow-up as SAM validate the count is added in the SAM edit the follow-up to MAM, and validate the count is removed from the SAM and added in the MAM.
8. Register the individual, enroll in the child program complete the chid follow-up as MAM validates the count is added in the MAM edit the follow-up to SAM, and validate the count is removed from the MAM and added in the SAM.
9. Void the individual will as the SAM and validate the count is removed from the dashboard card
10. Void the individual will as the MAM and validate the count is removed from the dashboard card
11. Edit the individual will as the SAM and validate that the count is removed from the dashboard card
12. Edit the individual will as the MAM and validate that the count is removed from the dashboard card
13. According to weight and height the nutrition status should be updated in the summary 
14. Edit the weight and height and validate the status is updated in the summary 
15. MUAC child if we give the value as 0 - 11.49 the status should be SAM
16. MUAC child if we give the value as 11.50 - 12.59 the status should be MAM
17. MUAC child if we give the value as >12.60 the status should be Normal.
18. Un-void the individual will as the SAM and validate the count is readded from the dashboard card
19.  Undo exit the individual will as the SAM and validate the count is readded from the dashboard card


Test Execution:
https://drive.google.com/drive/folders/1gsCxJ-pwRDXW4g8iCoPtQSHBn-mSbhct





Bugs:
1. We have the follow-up card to fix this 
https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0JCQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4d2fabd93139b270ec4962a4005ac420f0756345/SAM%20dashboard%20.mov
2.We have to update the nutrition status as per MCU child value what happen if we have the Current nutritional status according to weight and height as MAM then i can able to see the value change between sam and mam
for example (if the weight and height is calculated MAM if i give the MCU value as 11 then nutrition value is displayed as SAM and i edit to MAM but if i give the value as 13 then still the status show as MAM (are per the businnes logic it is depends of the weight and height the value are not updated ) hence we are ignoring this bug
3.Then in the summary can we highlighted sam and mam in the red (in the summary if we have it as high risk then only we can have them in highlighted as we dont have the requirment and also the businees logic we are ignoring  this bug for now)
4.Cohort wise report takes more than 2minutes avareage timing 2m29s54ms

**Comment by Dinesh2019** [comment]
@BEULAHEVANJALIN For MACU if we give the value as 12.51 still shows as MAM but it should be shown as Normal which we fixed already don't know why it is showing again 

Fixed the issues 

https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGZrQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--765c6dd527cedf4f0fdebf798793a2d93681ec52/Screen%20Recording%202023-11-17%20at%201.18.27%E2%80%AFPM.mov

**Comment by BEULAHEVANJALIN** [comment]
@Dinesh2019 The reason you are not seeing "Current nutritional status according to weight and height" value when you input 33 is because there is no valid height value less than 45 for newborn babies. Newborn babies are not typically shorter than 45 centimeters, and as a result, the calculation for wfh may not provide meaningful results for such low height values.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1BrQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0d85ddde8588d422c3555350b20d07ddc67a19de/image.png)
