### ISSUE TITLE
[SNCU Support] ETL Task generated and task completed 

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/SNCU#56]
Freshdesk: https://avni.freshdesk.com/a/tickets/2294
Since writing generic query was consuming lot of time and effort, QA this report via pointing it to pre release environment

- [x] Aggregate - Task generated and task completed 
- [x] Linelist - Task generated and task completed

**Comment by vedfordev** [comment]
as report already build by other developer and test is pending, I created new folder for org **sncu_uat** and changed query, parameter, and other things. still not working need to debug further.

**Comment by Dinesh2019** [comment]
Count added in both SAM and MAM but excepted count should be added only in SAM or MAM according to the scenario

**Comment by Dinesh2019** [comment]
In the line list add the new column which has the DEA URL for that encounter

**Comment by vedfordev** [comment]
@Dinesh2019 link added once check

**Comment by Dinesh2019** [comment]
@vedfordev  we have to fix the logic of normal and no status card because if i have completed the follow-up as normal the count is added in the no status except the count should be added in the normal children(7 months to 5 years)
2. This individual Test norma dinnov1102 has an age of 6 months but it is displayed under the no status of (7 months to 5 years)

**Comment by vedant** [comment]
Hey @Dinesh2019 , I think you inadvertently mentioned me.

**Comment by nupoorkhandelwal** [comment]
Task done under this card --

- [x] 1. Updated aggregate query for children 7 to 60 months - (Logic used to update this - Get count under each status when the task/visit was generated and completed)
- [x] 2. Updated linelist "Task generated child nutrition" to share same select filter from the aggregate 
- [x] 3. Update aggregate query for children 0 to 6 months ( use same count and filter checks as done in the 7 to 60 months agg query) 
- [x] 4. Update linelist "Task generated child grade" report to share same select and filters from the respective agg query.
- [ ] 5. Test thoroughly all the filters, drill down and links to DEA for ind and enc.

**Comment by Gojo-Taqi** [comment]
Both the aggregate and the linelist needs fixing, even after adding the logic to fetch the previous status, it gives wrong results.

**Comment by Dinesh2019** [comment]
We have register the child and done the followup as Sam and second followup as MAM but the count is added both in SAM and MAM

**Comment by nupoorkhandelwal** [comment]
Queries to test the report -

`select LAG(observations ->> '3fb85722-fd53-43db-9e8b-d34767af9f7e'::text, 1) OVER (
    PARTITION BY program_enrolment_id ORDER BY encounter_date_time asc
    )                                                             previous_nutritional_status,* from program_encounter
left join sncu_uat.address on address_id = address.id
left join sncu_uat.individual on individual_id = individual.id
where
    "Block" = 'Valia' and
    (EXTRACT(year FROM age(individual.date_of_birth)) * 12 +
     EXTRACT(month FROM age(individual.date_of_birth)))  between 7 and 60
order by earliest_visit_date_time , individual_id desc;`

`
select LAG(observations ->> '3fb85722-fd53-43db-9e8b-d34767af9f7e'::text, 1) OVER (
    PARTITION BY program_enrolment_id ORDER BY encounter_date_time asc
    )                                                             previous_nutritional_status,* from program_encounter
                                                                                                         left join sncu_uat.address on address_id = address.id
                                                                                                         left join sncu_uat.individual on individual_id = individual.id
where
        "Block" = 'Dediyapada' and
    (EXTRACT(year FROM age(individual.date_of_birth)) * 12 +
     EXTRACT(month FROM age(individual.date_of_birth)))   between 0 and 6
order by earliest_visit_date_time , individual_id desc;`

**Comment by Dinesh2019** [comment]
- [x] When applying the filter we get the data breaks 

https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGJ2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c24f15fe3c95d3e0d4c4b8ea29969ae1505bfbb7/Screen%20Recording%202024-03-19%20at%202.44.11%E2%80%AFPM.mov

**Comment by Dinesh2019** [comment]
- [x] After applying the filter if we click on the value in the report the report gets break

<img width="1235" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFgxQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--30f986601c3b299000fe3276a3362a618fbc6d99/Screenshot%202024-03-20%20at%202.50.01%E2%80%AFPM.png" alt="Screenshot 2024-03-20 at 2.50.01 PM.png" />
