### ISSUE TITLE
[SNCU Support] Visit scheduling issues

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/SNCU#57]
**Support ticket** - https://avni.freshdesk.com/a/tickets/3085
**Support ticket** - https://avni.freshdesk.com/a/tickets/3088

**Prod org** - SNCU
**UAT org** - SNCU UAT

**NOTE** - Before making changes on UAT, take bundle upload from prod but check that there are no changes on UAT that are not pushed to prod. All the below issues need to be reproduced and then fixed.

- [ ] Issue 1 - As seen in the screenshot, same day visit is getting scheduled on completing the current visit.
- [ ] Issue 2 - For Low birth weight child, visit is getting scheduled for next year.
- [ ] Issue 3- On cancelling followup visits , same day visit is getting scheduled.

**Comment by BEULAHEVANJALIN** [comment]
Only uploaded the prod bundle to uat. Need to find out the error-ed encounter

**Comment by vedfordev** [comment]
## Developer Note:



#### PNC
For pnc find issue in cancel visit. Changed the rule and done with following testing

#### Test Scenario for pnc cancellation
1. First Pnc with low weight - scheduling in next 7 days
2. First Pnc with normal weight - scheduling next pnc in next 28 days
3. Second Pnc with low weight - schduling in next 7 days
4. Second Pnc with normal weight - scheduling next pnc in next 28 days


#### Child Followup

**individual :** Jiyansh Nita gautam mashing(1409909) dob : 2023-08-01

1. indiviudal enroled in child program and as per logic (age<2) in enrolment it shceduled child pnc(2424752)
2. pnc filled with weight 3.45 and age< 2 . So it should schedule only pnc as per current rule but unable to figure out how it schdule followup.
(Need to furthure debug)

```
const out = document.getElementById('output');

const someday = moment("2024-01-06");
const today = moment("2023-09-18");
const catday = moment("2023-08-01");

const diff = today.diff(someday, 'days');
const catdiff = today.diff(catday, 'months');

console.log("diff",diff);
console.log("catdiff",catdiff);

```

**Comment by Dinesh2019** [comment]
The bug card: avniproject/avni-models#49

currently, we can't handle the edit encounter scenario. It is not raised by the client.

**Comment by vedfordev** [comment]
[SNCU.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmRlQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6926edbf52bc17299df1774f7fa4cd95f05000c4/SNCU.zip)

**Comment by vedfordev** [comment]
@nupoorkhandelwal 
 
Only changed cancellation rule for pnc and enrolment visit scheduling rule.
