### ISSUE TITLE
[SNCU] Child Followup form

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/SNCU#6]
https://docs.google.com/spreadsheets/d/1DJzjWi_Pde0pDQLdDNTzG3QkrJZ1MREs/edit#gid=2072499313

Form changes
Visit scheduling

**Comment by garimadosar5** [comment]
QA Notes - 
- Current nutritional status according to weight and height is not showing. **For which individual? Hope height was <= 120 cm!!**
- Case - Simple Patil. The first followup is scheduled on 14 Oct 2020 and next is scheduled on 27 May 2021.
But in case of Normal status and age 2 years, it should schedule followup after 4 months. that will be 14 Feb 2021.
And on cancel it is scheduling next visit for 25 Aug 2021. i.e 3 months after scheduled visit(27 may 21). **Fixed**

**Comment by garimadosar5** [comment]
**QA Notes 2 -** 
- Case - Dolly Singh. 
1st Follow-up visit  is scheduled on 14 oct and child is SAM so next visit should be scheduled after one month i.e. 14 Nov 20.
but it is scheduling on 14 feb 2021.

**Please check. The nutritional status shows Normal right now!!**
