### ISSUE TITLE
move changes from UAT to production

### ISSUE THREAD

**Issue by salilsamanvay** [avniproject/SNCU#61]
## Context: 
we have given the changes to the client for testing on UAT and now the client has given the acceptance, so we will have to move the changes in this epic to live org

UAT org : SNCU_UAT
live org : SNCU

once changes are moved to live org, we will test the same on production and hand it over to the client.

Note: please keep a backup of live org before moving the UAT bundle to live, so that if things don't work properly we can roll back the changes.

**Comment by BEULAHEVANJALIN** [comment]
UAT bundle: [SNCU_UAT.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUlYQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--59b256282664ea2f7f651c89fa754b22ccbdfbf1/SNCU_UAT.zip)

Prod bundle before upload: [SNCU.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVVYQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--379cc6d7a714b2d2d2ff2c22cd146e93e08abe43/SNCU.zip)
