### ISSUE TITLE
{Sewa Rural New} Metabase Spike Testing

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/SNCU#65]
Need to do the Spike Testing for [Prevalance of Anemia ](https://reporting.avniproject.org/dashboard/258-prevalance-of-anemia)Report

**Comment by adamsanadi6** [comment]
[Dashboard Link](https://reporting.avniproject.org/dashboard/268)

**Comment by Dinesh2019** [comment]
@adamsanadi6 

- [x] Need to have Individual Names displayed in the report which makes the user identify easy
