### ISSUE TITLE
[SNCU] Reschedule visit when child not available at home

### ISSUE THREAD

**Issue by arjunk** [avniproject/SNCU#66]
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHFwQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--67b04b329f525a4741ec1e322fdfb0a3172cb1c3/image.png" alt="image.png" />

## Acceptance Criteria

- [x] 1. In "Program Encounter Cancellation Form" add one more answer option "Child not at home"
- [x] 2. Gujarati translation બાળક ઘરે નથી
- [x] 3. When the visit is cancelled with this option selected, it should schedule the same visit for 7 days after the cancelled date, make it overdue 4 days after. 

## Workflow
- Check with fresh dev team if they are working on SNCU
- if not, take the bundle from prod to UAT to get UAT to latest prod
- Make changes on UAT
- Share with Dr Dhiren to validate
- Once validated, move it to prod
- Inform Dr Dhiren on ticket and mark it resolved
- live happily ever after!

## Technical
Prod org : SNCU
UAT org : SNCU_UAT

**Comment by Gojo-Taqi** [comment]
Got an error on bundle upload. Created a ticket and assigned it to the Product support group.
https://avni.freshdesk.com/a/tickets/3928

**Comment by Gojo-Taqi** [comment]
The error didn't yet get resolved, have assigned the ticket back to product.
Moving the card back to ready, shall pick up once the ticket is closed.
