### ISSUE TITLE
[SNCU] Child Cancel form

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/SNCU#7]
https://docs.google.com/spreadsheets/d/1DJzjWi_Pde0pDQLdDNTzG3QkrJZ1MREs/edit#gid=1010348875

**Comment by garimadosar5** [comment]
QA Notes - 
- If child is Parmanent migrated or dead then also it schedule new visit. Check once if that is the accepted behaviour.

**If the child is migrated/dead ,ideally the individual is exited from the program. And then on cancel we don't generate visits for exited programs. For other implementations as well, it is implemented the same way**
